apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
spec:
  selector:
    matchLabels:
      app: shop-backend
  replicas: 3
  template:
    metadata:
      labels:
        app: shop-backend
    spec:
      containers:
        - name: shop-backend
          image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:1.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
#          envFrom:
#            - secretRef:
#                name: shop-database
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
      restartPolicy: Always
