apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.name | default "shop-frontend" }}
  labels:
    {{- toYaml .Values.frontend.matchLabel | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- toYaml .Values.frontend.matchLabel | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.frontend.matchLabel | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.frontend.name | default "shop-frontend" }}
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
