apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name | default "shop-frontend" }}
  labels:
    {{- toYaml .Values.frontend.matchLabel | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- toYaml .Values.frontend.matchLabel | nindent 4 }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
