image: registry.gitlab.com/codelab-kubernetes/workshop:gitpod-workspace
tasks:
  - before: code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
  - command: curl --user devfest-nantes-2024:${PACKAGE_REGISTRY_PASSWORD} https://gitlab.com/api/v4/projects/61280261/packages/generic/devfest-nantes/20241017/kubeconfig.yml --output ${HOME}/.kube/config