apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shop
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.hostnames.ingress }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.names.frontend | default "shop-frontend" }}
                port:
                  number: {{ .Values.ports.frontend }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.names.backend | default "shop-backend" }}
                port:
                  number: {{ .Values.ports.backend }}
