backend:
  name: shop-backend
  image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:database
  replicas: 3
  matchLabel:
    app: shop-backend
  port: 8080
  hpa:
    maxReplicas: 10
    cpuUtilization: 50
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

frontend:
  name: shop-frontend
  image: registry.gitlab.com/codelab-kubernetes/apps/shop-frontend:latest
  replicas: 1
  matchLabel:
    app: shop-frontend
  port: 80
  resources:
    requests:
      memory: "32Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"

database:
  name: shop-database
  image: registry.gitlab.com/codelab-kubernetes/apps/shop-database:latest
  replicas: 1
  matchLabel:
    app: shop-database
  port: 5432
  storage: 1Gi
  resources:
    requests:
      memory: "64Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  connection:
    databaseName: "shop"
    password: "postgres"

ingress:
  hostname: "helm-<student-X>.devshop.codelab.dwidwi.tech"
