apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.names.backend | default "shop-backend" }}
  labels:
    app: {{ .Values.labels.backend | default "shop-backend" }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.labels.backend | default "shop-backend" }}
  ports:
    - port: {{ .Values.ports.backend }}
      targetPort: {{ .Values.ports.backend }}
