apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name | default "shop-backend" }}
  labels:
    {{- toYaml .Values.backend.matchLabel | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- toYaml .Values.backend.matchLabel | nindent 4 }}
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
