apiVersion: v1
kind: Pod
metadata:
  name: shop-backend
  labels:
    app: shop-backend
spec:
  containers:
    - name: shop-backend
      image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:1.1.0
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "32Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
