apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend
spec:
  selector:
    matchLabels:
      app: shop-backend-label
  replicas: 3
  template:
    metadata:
      labels:
        app: shop-backend-label
    spec:
      containers:
        - name: shop-backend
          image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:database
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://shop-database-service:5432/shop
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shop-database-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
