apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-backend-deployment
spec:
  selector:
    matchLabels:
      app: shop-backend-label
  replicas: 3
  template:
    metadata:
      labels:
        app: shop-backend-label
    spec:
      containers:
        - name: shop-backend-container
          image: registry.gitlab.com/codelab-kubernetes/apps/shop-backend:no-database
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
