apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name | default "shop-database" }}
  labels:
    {{- toYaml .Values.database.matchLabel | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  clusterIP: None
  selector:
    {{- toYaml .Values.database.matchLabel | nindent 4 }}
