apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name | default "shop-database" }}
  labels:
    {{- toYaml .Values.database.matchLabel | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- toYaml .Values.database.matchLabel | nindent 6 }}
  serviceName: {{ .Values.database.name | default "shop-database" }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.database.matchLabel | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.database.name | default "shop-database" }}
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.port }}
          resources:
            {{- toYaml .Values.database.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.database.name | default "shop-database" }}
            - secretRef:
                name: {{ .Values.database.name | default "shop-database" }}
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.database.storage }}
